version: '3.4'

services:
    db:
        image: 'postgres:10.1-alpine'
        environment:
            POSTGRES_USER: 'jef'
            POSTGRES_PASSWORD: 'yourpassword'
        volumes:
            - 'db:/var/lib/postgresql/data'
volumes:
    db:
